### ISSUE TITLE
Worktree-specific config

### ISSUE THREAD

**Issue by hakoerber** [hakoerber/git-repo-manager#15]
A TOML in the root of a worktree like this:

```toml
persistent_branches = [
    "master",
    "develop",
]

[track]
default = true
default_remote = "origin"
default_prefix = "myprefix"
```

`persistent_branches` will be used for:

* `grm wt clean` will never clean up these branches
* `grm wt clean` will clean branches that are merged into these persistent branches
* `grm wt delete` does not require `--force` if the branch is merged into these persistent branches

`default_track` will automatically add a tracking branch on `grm wt add`. By default, it will track `origin/{branchname}`. The remote can be configured with `default_track_remote`, and a prefix can be given with `default_track_remote`. Prefix is used like `{remote}/{prefix}/{branchname}`
