### ISSUE TITLE
handling nested repositories

### ISSUE THREAD

**Issue by pythys** [hakoerber/git-repo-manager#48]
So I have some projects that simply hold git repositories inside other git repositories (usually in .gitignore folders). And I want to keep that directory structure. Is this possible without introducing submodules?

**Comment by pythys** [comment]
OK answering myself, things are a little more clear to me now

`grm repos find local` this command will _not_ find nested repos however you can do it manually and it will work. Now the problem is order sequence, but I suppose this is easily solved by making the root repos clone before the sub-repos. Example below

```
- root: ~/projects
  repos:
  - name: mainproject
    worktree_setup: false
    remotes:
    - name: origin
      url: https://github.com/whatever/whatever.git
      type: https
  - name: mainproject/subproject
    worktree_setup: false
    remotes:
    - name: origin
      url: https://github.com/whatever/whateverelse.git
      type: https
```
