### ISSUE TITLE
Add global configuration & default tracking

### ISSUE THREAD

**Issue by hakoerber** [hakoerber/git-repo-manager#5]
This would enable features like a "default-tracking", with a prefix. An example config:

```toml
default_tracking_enabled = true
default_tracking_prefix = "myprefix"
```

This would mean that a branch `branch` would be set up to track `origin/myprefix/branch` by default.
