### ISSUE TITLE
SSH error cloning repositories Gitlab

### ISSUE THREAD

**Issue by theherk** [hakoerber/git-repo-manager#61]
I am using a private Gitlab host, with successful API connection.

Configuration is:

```toml
provider = "gitlab"
api_url = "https://gitlab.something"
token_command = "security find-generic-password -w -s gitlab.something -a theherk@gmail.com"
root = "."

[filters]
owner = true
groups = [
  "some/group",
]
```

This finds all repositories as expected, but on `grm repos sync config` all the clones yield:

```
Cloning into "./some/group/repo" from "ssh://git@gitlab.something:2222/some/group/repo.git"
Repository failed during clone: remote rejected authentication: Failed getting response; class=Ssh (23); code=Auth (-16)
```

But I can `git clone ssh://git@gitlab.something:2222/some/group/repo.git` without a problem.

`~/.ssh/config`

```
Host *
  IdentityFile ~/.ssh/id_ed25519
  UseKeychain yes
  HostKeyAlgorithms ssh-ed25519
  PubkeyAcceptedKeyTypes ssh-ed25519
```

---

This is actually taking place in public Gitlab too with the same error.

### Maybe related

- [cargo generate using ssh results in: Git Error: Failed to authenticate SSH session: ; class=Ssh (23)](https://stackoverflow.com/q/72542219/2081835)
