### ISSUE TITLE
Get specific project from forge?

### ISSUE THREAD

**Issue by theherk** [hakoerber/git-repo-manager#62]
Say I have a working configuration like:

```toml
provider = "gitlab"
api_url = "https://gitlab.private"
token_command = "security find-generic-password -w -s gitlab.private -a theherk"
root = "."

[filters]
owner = true
groups = [
  "foo",
]
```

This gets all the projects from group `foo`, but what if I want to get a specific project from `bar`? For example, this doesn't work:

```toml
provider = "gitlab"
api_url = "https://gitlab.private"
token_command = "security find-generic-password -w -s gitlab.private -a theherk"
root = "."

[filters]
owner = true
groups = [
  "foo",
]

[[trees]]
root = "./bar"

[[trees.repos]]
name = "bar"
worktree_setup = false

[[trees.repos.remotes]]
name = "origin"
url = "ssh://git@gitlab.private/bar/baz.git"
type = "ssh"
```

It yields `expected struct ConfigProvider`.
