### ISSUE TITLE
cannot sync found projects.

### ISSUE THREAD

**Issue by woutervh** [hakoerber/git-repo-manager#65]
what am  i doing wrong:

first I created a config-file with:
```
> grm repos find remote --provider gitlab --token-command "echo ${GITLAB_TOKEN}" --root repo --format yaml --group my-projects  > gitlab-projects.yaml
```
This finds all my-projects correctly:

```
trees:
- root: repo
  repos:

  - name: foo
    worktree_setup: false
    remotes:
    - name: origin
      url: git@gitlab.com:my-projects/foo.git
      type: ssh
     ....
```

manually cloning this repo works ok
```
> git clone git@gitlab.com:my-projects/foo.git
```

but syncing via grm fails
```
>  grm repos sync config --config gitlab-projects.yaml
```

```
remote: ========================================================================
remote:
remote: ERROR: The project you were looking for could not be found or you don't have permission to view it.

remote:
remote: ========================================================================
remote:
; class=Ssh (23); code=Eof (-20)
```
