### ISSUE TITLE
feat: more support for worktrees

### ISSUE THREAD

**Issue by colemickens** [hakoerber/git-repo-manager#66]
Hi,

If I'm not mistaken, `grm` feels like a mix of declarative and imperative right now. While my repos are managed via the config file, it doesn't seem like worktrees are? That's from peeking at the config rust code, and just from my initial tests.

Stated another way - In the pursuit of having GRM be part of an ephemeral dev setup, I want to be able to feed GRM a config file that notes worktrees and their tracked remote branches, to re-instantiate my code tree.

I imagine something like:

```
trees:
- root: ~/code2
  repos
  - name: home-manager
    worktrees:
    - branch: main
      path: main/ # relative to the repo location
      tracks: origin/main
    - brach: cmhm
      path: cmhm/
      tracks: origin/cmhm
    remotes:
    - name: origin
      url: https://github.com/colemickens/home-manager
      type: https
```

I'm also thinking about the general UX of this, I almost want to be able to block the checkout/switching of branches except through GRM (even better, make the user edit the config file and re-run GRM to "realize" their code tree). I doubt that's possible though.

Maybe this is not a novel idea, but rather just not implemented yet?
