### ISSUE TITLE
Github Enterprise Support

### ISSUE THREAD

**Issue by theherk** [hakoerber/git-repo-manager#78]
I use this currently with Github, Gitlab, and self-hosted Gitlab. But I need to use it with Github Enterprise, also.

I'd like to use a config like:

```toml
force_ssh = true
provider = "github"
api_url = "https://api.foo.ghe.com"
token_command = "security find-generic-password -w -s foo.ghe.com -a theherk@foo.com"
root = "."

[filters]
owner = true
```

But API override is not supported for Github. Before I fumble around with attempting to make that possible, is there some reason it is not supported, or just nobody else needed it yet?
